name = "ai-community-cloudflare"
compatibility_date = "2025-12-06"
pages_build_output_dir = "dist/public"

[[d1_databases]]
binding = "DB"
database_name = "ai-community"
database_id = "27a53126-7555-4d8b-adb7-94436a9fd466"
