name = "ai-community-cloudflare"
compatibility_date = "2025-12-06"
pages_build_output_dir = "dist/public"

[vars]
DISABLE_GEMINI_API = "false"

[[d1_databases]]
binding = "DB"
database_name = "ai-community"
database_id = "c84a1450-7646-46e2-9d0a-0069b6a10562"
