name = "ai-community-cloudflare"
compatibility_date = "2025-12-06"
pages_build_output_dir = "dist/public"

[vars]
AUTO_CHAT_INTERVAL_SECONDS = "10"

[[d1_databases]]
binding = "DB"
database_name = "ai-community"
database_id = "85788d53-f633-4e39-8b65-5f07103369e6"
